# Generated by Django 4.0.4 on 2022-04-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=400)),
                ('image', models.FileField(upload_to='books/static/books/images/')),
                ('price', models.IntegerField()),
                ('published_at', models.DateField()),
                ('add_to_site_at', models.DateTimeField(auto_now_add=True)),
                ('appropriate_to', models.CharField(choices=[('-8', 'Under 8'), ('+8', '8-15'), ('+15', 'Adults')], max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minBooks.author')),
            ],
        ),
    ]
